steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sairajapp:$COMMIT_SHA', '.']

# Step 2: Push the Docker image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sairajapp:$COMMIT_SHA']

# Step 3: Update the container on the Compute Engine instance
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'instances'
    - 'update-container'
    - 'flask-instance'
    - '--zone=us-central1-a'
    - '--container-image=gcr.io/$PROJECT_ID/sairajapp:$COMMIT_SHA'

images:
- 'gcr.io/$PROJECT_ID/sairajapp:$COMMIT_SHA'
